# Generated by Django 5.1.7 on 2025-03-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
