# Generated by Django 5.1.7 on 2025-03-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_file_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
